apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: markets-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - markets.prodv2.cedille.club
      secretName: markets-tls
  rules:
    - host: markets.prodv2.cedille.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: markets-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: markets-backend-service
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: markets-backend-service
                port:
                  number: 80
          - path: /verification
            pathType: Prefix
            backend:
              service:
                name: markets-backend-service
                port:
                  number: 80
          - path: /static/admin
            pathType: Prefix
            backend:
              service:
                name: markets-backend-service
                port:
                  number: 80
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: markets-backend-service
                port:
                  number: 80
